Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Connector Configuration
        Parameters:
          - AWSSecretName
          - SlackEndpointURL
      - Label:
          default: Lambda Function Configuration
        Parameters:
          - LambdaFunctionName
          - SpillBucket
          - SpillPrefix
          - DisableSpillEncryption
          - LambdaTimeout
          - LambdaMemory
    ParameterLabels:
      AthenaCatalogName: Lambda Name
Parameters:
  LambdaFunctionName:
    Description: The name you will give to lambda function. This name must satisfy the pattern ^[a-z0-9-_]{1,64}$
    Type: String
    AllowedPattern: ^[a-z0-9-_]{1,64}$
    Default: slackmemberanalytics
  SlackEndpointURL:
    Description: Slack Analytics data endpoint.
    Type: String
    Default: https://slack.com/api/admin.analytics.getFile
  AWSSecretName:
    Description: AWS Secret name where Slack API token is stored.
    Type: String
  SpillBucket:
    Description: Specify the name of an S3 bucket where this function can spill data.
    Type: String
  SpillPrefix:
    Description: The prefix within SpillBucket where this function can spill data.
    Type: String
    Default: athena-spill
  LambdaTimeout:
    Description: Maximum Lambda invocation runtime in seconds. (min 1 - 900 max)
    Default: 900
    Type: Number
  LambdaMemory:
    Description: Lambda memory in MB (min 128 - 3008 max).
    Default: 3008
    Type: Number
  DisableSpillEncryption:
    Description: 'WARNING: If set to ''true'' encryption for spilled data is disabled.'
    Default: 'false'
    Type: String
Resources:
  ConnectorConfig:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          disable_spill_encryption: !Ref DisableSpillEncryption
          spill_bucket: !Ref SpillBucket
          spill_prefix: !Ref SpillPrefix
          data_endpoint: !Ref SlackEndpointURL
          region: !Ref AWS::Region
          secret_name: !Ref AWSSecretName
      FunctionName: !Ref LambdaFunctionName
      Handler: com.amazonaws.connectors.athena.slack.SlackCompositeHandler
      CodeUri: s3://quicksight.slackanalytics.afqconnector/athena-slack-member-analytics-1.0.jar
      Description: A sample connector for accessing Slack Member Analytics API data via Amazon Athena Federated Query.
      Runtime: java8
      Timeout: !Ref LambdaTimeout
      MemorySize: !Ref LambdaMemory
      Policies:
        - Statement:
            - Action:
                - athena:GetQueryExecution
                - s3:ListAllMyBuckets
              Effect: Allow
              Resource: '*'
            - Action:
                - secretsmanager:GetSecretValue
              Effect: Allow
              Resource: !Join
                  - ''
                  - - 'arn:'
                    - !Ref AWS::Partition
                    - ':secretsmanager:'
                    - !Ref AWS::Region
                    - ':'
                    - !Ref AWS::AccountId
                    - ':secret:'
                    - !Ref AWSSecretName
                    - '*'
          Version: '2012-10-17'
        - S3CrudPolicy:
            BucketName: !Ref SpillBucket